apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-redis-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Delete
  nfs:
    server: 192.168.100.72
    path: /nfsroot/redis/
