apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: default
  name: redis
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: redis
rules:
- apiGroups:
  - ""
  resources:
  - endpoints
  - pods 
  verbs: 
  - get
  - watch
  - list
- apiGroups: ["apps"]
  resources:
  - statefulsets
  verbs: 
  - get
  - watch
  - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  namespace: default
  name: redis
subjects:
  - kind: ServiceAccount
    name: redis
    namespace: default
roleRef:
  kind: Role
  name: redis
  apiGroup: rbac.authorization.k8s.io
